language: java
jdk:
 - oraclejdk8
deploy:
  provider: releases
  api_key: "$oauth_token"
  file: "target/guttenberg-$TRAVIS_TAG.jar"
  skip_cleanup: true
  draft: true
  on:
    branch: master
    tags: true